# Generated by Django 3.1.5 on 2021-01-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='subjects',
        ),
        migrations.AddField(
            model_name='commontimetable',
            name='available_time',
            field=models.CharField(default='5-6', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commontimetable',
            name='standard',
            field=models.CharField(default='1-4', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commontimetable',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.student'),
        ),
        migrations.AddField(
            model_name='teacherreg',
            name='available_time',
            field=models.CharField(default='1-4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerreg',
            name='available_time',
            field=models.CharField(default='1-4', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherreg',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherreg',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicapp.subjects'),
        ),
    ]
