# Generated by Django 3.1.5 on 2021-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_auto_20210131_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interplacement',
            name='interplacement_id',
        ),
        migrations.AddField(
            model_name='interplacement',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
