# Generated by Django 3.1.5 on 2021-01-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0005_auto_20210131_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interplacement',
            old_name='course_id',
            new_name='course',
        ),
    ]
