# Generated by Django 3.1.5 on 2021-01-31 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0008_leavereportstaff_leavereportstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
