# Generated by Django 3.1.5 on 2021-01-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0011_studentsattending_timetable'),
        ('publicapp', '0011_exam_result'),
    ]

    operations = [
    ]
